branch-defaults:
  master:
    environment: app-env
global:
  application_name: app
  default_ec2_keyname: ca-magalhaes1-oregon
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Python 2.7
  default_region: us-west-2
  profile: null
  sc: git
